services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=explorewithme
      - SPRING_DATASOURCE_PASSWORD=explorewithme

  stats-db:
    image: postgres:16.1
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=explorewithme
      - POSTGRES_USER=explorewithme
      - POSTGRES_DB=explorewithme
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=explorewithme
      - SPRING_DATASOURCE_PASSWORD=explorewithme
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=explorewithme
      - POSTGRES_USER=explorewithme
      - POSTGRES_DB=explorewithme
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
